[deploy]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps"
startCommand = "node start.js"
healthcheckPath = "/health"
healthcheckPort = "8080"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "5000"
MONGODB_URI = "mongodb+srv://kingrohi37:repurandi@cluster0.resuock.mongodb.net/finnsathi?retryWrites=true&w=majority&appName=Cluster0"
NODE_ENV = "production"
